version: 2
updates:
  - package-ecosystem: npm
    directory: /phantom-website-dashboard
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: nuget
    directory: /phantom-windows-app-backend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: nuget
    directory: /phantom-dashboard-backend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
